[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200